### ISSUE TITLE
PUT Operation crashes node process

### ISSUE THREAD

**Issue by kukku-me** [jitendra5984/mysql-restapi#1]
I am trying to use mysql-restapi package and am facing issue while I use put to update the record,the error I get is following on command line from where I start the process 

$node app.js
/u01/mysqlrest/myapp/myapp/node_modules/mysql/lib/protocol/Parser.js:80
        throw err; // Rethrow non-MySQL errors
        ^

ReferenceError: connection is not defined
    at Object.module.exports.sendSuccessAnswer (/u01/mysqlrest/myapp/myapp/node_modules/mysql-restapi/lib/functions.js:26:18)
    at Query._callback (/u01/mysqlrest/myapp/myapp/node_modules/mysql-restapi/lib/api.js:411:35)
    at Query.Sequence.end (/u01/mysqlrest/myapp/myapp/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
    at Query._handleFinalResultPacket (/u01/mysqlrest/myapp/myapp/node_modules/mysql/lib/protocol/sequences/Query.js:139:8)
    at Query.OkPacket (/u01/mysqlrest/myapp/myapp/node_modules/mysql/lib/protocol/sequences/Query.js:72:10)
    at Protocol._parsePacket (/u01/mysqlrest/myapp/myapp/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/u01/mysqlrest/myapp/myapp/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/u01/mysqlrest/myapp/myapp/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/u01/mysqlrest/myapp/myapp/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)

Any insights will be very helpful ,infact POST/DELETE works fine.

**Comment by jitendra5984** [comment]
solved 
thanks @danfercf1
